### ISSUE TITLE
Version control of R libraries

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#1]
Software version info matching is important for pipeline reproducibility. For single executable type of software it is the users responsibility to provide and install so what SOS can do is perhaps record it somewhere, e.g., `sos_session_info.txt`. But SOS automatically installs R libraries which may cause problems with versions. A simply way out would be using these syntax for R library: `package_host/package_name/version`. For example, `cran/ggplot2/0.99` and `bioc/ggbio/xxx` and even github R packages `username@github/package` (for github perhaps there are no version but commit/tag instead?).

**Comment by bpeng2000** [comment]
Unlike RMarkdown, SoS does not understand the underlying language and interpreter. It also does not have a default output so there is no place to save package information even if R('sessionInfo()') is called.  Reproducibility is currently maintained by checking version of tools (checkCmd('R --version', '3.0.2') with a warning or error when a different version of R is used. The action can also save its output somewhere, e.g. R('sessionInfo()', stdout='session.info'), but I do not see a universal solution to this problem.

**Comment by gaow** [comment]
I think different R versions is less of an issue, but rather different R package versions that SOS tries to install (always the latest). A lot R packages are not maintained with backward compatibility and that's why I was suggesting `CheckRLibraries(host/package/version, ...)` type of syntax to try to do it right (reproducibly) upfront. I understand `sessionInfo()` is not an option. This is a minor issue at this stage of development but I guess it does not harm to just keep a thought here.

**Comment by gaow** [comment]
It has been documented to Pending Problems page.
