### ISSUE TITLE
Read only SoS variable?

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#11]
A SoS can be easier to understand if we make most SoS variables readonly. That is to say, a SoS variable can not be changed
after it has been initialized. Exceptions to this rule can be system variables and temporary looping variables. It is also
possible to use _name for all non-readable variables.

Pros:
* This makes SoS less error prone.

Cons:
* It sometimes make sense to adjust existing variables. For example the `bam_files` in the option `skip` example.

**Comment by gaow** [comment]
Reminds me of c syntax like "#define pi 3.14" ... Perhaps use all capital convention for this type of variable? e.g., PI = 3.14. Usually people will not use all cap in their scripts. Also if this needs to be adjusted it is always possible to re-assign to a tmp var and adjust from there.

**Comment by bpeng2000** [comment]
Ok, I will implement the warning system.

Bo

**Comment by bpeng2000** [comment]
Done, along with warning for the use of name with leading _.
