### ISSUE TITLE
Implementation of input and output alias

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#12]
It is very useful to save input and output of a step to properly named variables so that later steps can refer to
them with their names. There can be three implementations

```python
[step_index: input_alias=name, output_alias=name]
```

Pros:

* Easy to notice and emphasize the proper names of input and output of the step.
* Make sure the variables are list of strings.

Cons:

* Special syntax (section option)
* Cannot define multiple variables for different outputs.

```python
[step_index]
name = step_input
name1 = step_output
stuff = step_output[0]
other = step_output[1:]
```

Pros:

* Use existing variable assignment mechanism
* Does not have to limit to `step_input` or `step_output`. For example, if there are two types of output files,
  you can separate them into several variables.

Cons:

* The variable can be a string instead of list of string depending on how it is assigned.
* Users need to know `step_index` and `step_output`, which is more or less internal
* it is currently unclear where to put these statements because statements after directive is step action, and statement before directives are evaluated without output information.

```python
input: alias=name
output: alias=name
```

Pros:

* No special syntax and no need to know `step_input`

Cons:

* Cannot define multiple variables for difficult outputs.
* Conceptually speaking input can have nothing to do with `step_input` and `name` should be filtered even `group_by` input files.

**Comment by gaow** [comment]
How important is it to expose a partial list of input / output to other steps as opposed to the entire input / output, and let users parse / slice them in other steps? If there is no harm doing that, I'm comfortable with your first proposal. After all you already have other `step_options` and it seems a natural place to go.

**Comment by bpeng2000** [comment]
It is sometimes important because for example, tophat produces bam file and
statistics and later steps will need to refer to them separately.

I think we can borrow python's syntax, namely, the entire list is set to A
for

A = list

and A1, A2 get the first and second item of A for

A1, A2 = list

That is to say, we can use

output_alias='aligned'

aligned = all output

output_alias = ['aligned', 'stat']

for aligned = first output, stat = second output, and the output must have
exactly two elements in this case.

**Comment by gaow** [comment]
It sounds like a good compromise and is very compact. It will work only for simple cases, though, because if you need slices from output it will not work. I tend to think we should either do nothing about it (output everything) or be flexible enough to alias any arbitrary slice, if possible. 

something like `output_alias = [('aligned', 1, 2, 4:6, 10), ('stat', 3, 7:9)]`? Also do we need `'`?

**Comment by bpeng2000** [comment]
I think it is good enough to provide solution to two most popular cases, whole list or individual item because it is easy to understand for Python users with least confusion about the type of outcome. Users for more difficult cases can define them later.

**Comment by gaow** [comment]
This looks a succinct solution and allows the possibility to index / slices after by users

**Comment by bpeng2000** [comment]
This has been implemented but 'alias' should be an alias to some existing item. I am wondering if we should produce variables such as `default_10` with input, output, index etc. On the other hand, using these variables should be strongly discouraged so we should not provide them in the first place. 

Another solution is to put `_step_input`, `_step_output` etc in a temporary structure (e.g. `_step.input`, `_step.output`, and alias is a way to turn this temporary structure permanent.
