### ISSUE TITLE
Default input of step?

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#13]
Would it clearer to require explicit input files? Right now the a step's `_step.input` is
the output of previous step. The problem with no default input is that step aliases are
almost always required and make the script a bit cumbersome.

Pros and cons of using default input:

pro:

* Avoid specifying input repeatedly
* Avoid using step alias. This could be avoided by adding runtime variables such as `input100`, but `input: output200` is not
  a good idea because the current step will be broken if step indexes are changed. A properly named variable is much better
  for this purpose.

cons:

* Input can change with change of location of step within a workflow. Things can get worse if users do not arrange steps in order, or use steps shared by multiple workflows etc.

**Comment by gaow** [comment]
I think it is clearer and safer to not use default input, because implicit dependency of steps and ordering of steps sounds rather dangerous. Snakemake uses your proposed solution, though:
```
rule do_something:
 ...
rule do_another_thing:
  input: rules.do_something.output
```

but in snakemake step order doesn't matter so it's a good design. This is not the case for us.

**Comment by bpeng2000** [comment]
Just note that VPT once used output100 etc and it was a huge mess if step 100 was changed.

Bo
