### ISSUE TITLE
Enforce naming convention?

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#15]
Does it make sense to force some name conversion so that users immediately know the type and nature of variables? This might
make the script a bit more readable. For example

1. Constant being string and all captical letters. (e.g. `RESOURCE_DIR='/path/to/resource'`)
2. Derived or temporary variables having leading underscore. (e.g. `_loop_variable`, `_label`, `_input`, right now `input` is used)
3. String and list of string having different name conversion? I hate perl's `$` and `@` symbols though.

By 'enforce', I mean SoS can give warning even error if a variable's usage does not match its name convention.

I tent to think we should let users use the style they prefer.

**Comment by gaow** [comment]
I agree with all cap for non-mutable variables. It seems we now use `${_xx}` for `for_each`. I do not like other conventions unless there is a compelling reason -- because it might be a good thing to have SoS appear as close as Python, not like Python + Perl ...

**Comment by bpeng2000** [comment]
I am not comfortable with

1. home instead of HOME because we get HOME from os.environ where its name
is HOME.
2. input being different from _loop_var. I tend to think all temporary
variables should be _named, especially when --input should be popular
command line arguments for SoS scripts.

I think we can

1. Use _name for all SoS generated variables that are local to each step.
That is to say, we use _input for local temporary input,  _loop, and _label
for loop and labels. We hide _step_input, _step_output, and _step_depends
(at least not document them) and users can only access them through
input_alias and output_alias.

2. Yield a warning if user defines a _named variable or changes a ALLCAP
variable, no error is needed, I think.

Bo

**Comment by gaow** [comment]
Sounds like good choice: ALLCAP is a widely acceptable convention for constants, so is using _ for private variables.
