### ISSUE TITLE
More workflow features (nested workflow, step library)

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#18]
SoS can certainly define a step with

```python
run('sos-runner anotherworkflow ${input}'
```

to execute another workflow, but it would be good to define another workflow from existing ones, or maintain a library of workflows.

**Comment by gaow** [comment]
Isn't it naturally supported ... ?

**Comment by bpeng2000** [comment]
I was thinking of something like:

workflow1: step 1, 2, 3, 4
workflow2: step 5, 6, 7, 8
default : workflow1 + workflow2

For example, workflow1 can be prepare and check of environment, workflow 2
can be execution. Then by default both are executed but later runs can skip
workflow 1.

Bo

**Comment by gaow** [comment]
How will this impact on the syntax of SoS?

**Comment by bpeng2000** [comment]
No idea yet. workflows are currently detected from section names and there
is no syntax for such usages.

**Comment by bpeng2000** [comment]
Syntax wise, we can do

```
[align_1]
[align_2]
[call_1]
[call_2]
[default=align+call]
```

This can even be expanded to create a step from part of another workflow,

```
[all_0]
[all_1=align1-10+call]
```
 
even #include feature such as

```
[all=anotherscript.align+anotherscript1.call]
```

It is a bit of hack to do include here but we would like to avoid introducing two much non-python syntax.

**Comment by bpeng2000** [comment]
Check test_parser testNestedWorkflow and see how it works. The implementation is quite crude (but simple) but can be extended to more complicated cases. We just need to figure out if this is useful, and give it a more careful implementation and testing later.

**Comment by gaow** [comment]
I can see this new feature will makes it easier for my planned interactions between DSC2 and pysos so I'll utilize and test it. My plan for this week is to get a version of DSC2 roughly running with pysos (previously was with snakemake) and learn / test SoS along the way.

**Comment by bpeng2000** [comment]
Right now, for 

```
[c=a]
input: ifiles
output: ofiles
process
```

SoS generates `_step.input`, execute `process`, set input of `a` to `_std_input`, execute `a`, and expect output `ofiles`. if input has loop, should subworkflow `a` be executed multiple times?

**Comment by gaow** [comment]
Is that part of the design and is it desired? If you allow for nested workflow of this fashion it makes SoS steps more modular, at the expense of clarity. Is there a scenario where you think it absolutely necessary to nest workflows in fashions other than simple `a + b + c ...`?

**Comment by bpeng2000** [comment]
If we are going to allow input, output, and runtime signature of the nested
step, it is conceptually simpler to consider nested workflow as part of the
step process, and can be executed multiple times. We can think of the
nested workflow as sub-steps to go from _input to output with its own
runtime signature (a workflow can be skipped if it is executed), whereas
each step of the workflow can have its own signature.

Other than A+B+C, this feature allows us to group steps and execute them
one or more times as a single step.... I have updated the documentation
with more explanation, although it would be difficult for users to
understand this section without reading other parts of the doc.
