### ISSUE TITLE
Logger message appears twice

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#2]
When I use `env.logger` from pysos.utils the logging message always appear twice. I remember I must have run into this before but I cannot recall the way out. I had to add `if not self._logger.handlers` to get rid of the duplicate, based on a random stackoverflow.com post. I am not sure if the problem occurs in the current SoS -- since I only used the `RuntimeEnvironment` class in my application something might be different, and the patch below is obviously not good because there are two types of handler `cout` and `ch` and I'm not dealing with it properly. Just want to know if this is an issue before taking any other actions. 

```diff
-        cout = logging.StreamHandler()
-        levels = {
-            '0': logging.WARNING,
-            '1': logging.INFO,
-            '2': logging.DEBUG,
-            '3': logging.TRACE,
-            None: logging.INFO
-        }
-        #
-        cout.setLevel(levels[self._verbosity])
-        cout.setFormatter(ColoredFormatter('%(color_levelname)s: %(color_msg)s'))
-        self._logger.addHandler(cout)
+        if not self._logger.handlers:
+            cout = logging.StreamHandler()
+            levels = {
+                '0': logging.WARNING,
+                '1': logging.INFO,
+                '2': logging.DEBUG,
+                '3': logging.TRACE,
+                None: logging.INFO
+            }
+            #
+            cout.setLevel(levels[self._verbosity])
+            cout.setFormatter(ColoredFormatter('%(color_levelname)s: %(color_msg)s'))
+            self._logger.addHandler(cout)
```

**Comment by bpeng2000** [comment]
I do not see this problem from test_utils.

        # create a logger, but shutdown the previous one
        if self._logger is not None:
            self._logger.handlers = []

is supposed to avoid this but I might have overlooked something.

Bo

**Comment by gaow** [comment]
It turns out I have imported like this in my test script:
```
from dsc import DSCData
utils import env
```
and in `DSCData` I also used `env`. There must then be a conflict. After I fixed python 3 compatibility and installed SOS, the following works:
```
from dsc import DSCData
from pysos.utils import env
```
So there will not be a problem if the package is properly installed.
