### ISSUE TITLE
Include or import etc.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#20]
Libraries would be python modules with defined SoS actions, but how to maintain and import these modules require further investigation. Furthermore, extensive use of libraries somehow beats the purpose of SoS (readability) because libraries hide the details of actions.

**Comment by gaow** [comment]
snakemake doesn't restrict the use of libraries ... I suppose the current support for import modules are perhaps sufficient: 

1. in python(''' ... ''') it is fully supported
2. `class` and `def` are also supported and one can always add an `import` statement inside a class or function if the class or function requires. There is then no need to have global support for this.

**Comment by bpeng2000** [comment]
This depends on what we want to include. snakemake uses a special include
directive to include rules. This is useful but something I dislike about
snakemake because for example tophat/STAR accept tones of parameters for
different applications and I do not want them to be hidden in another file.

SoS cannot include steps because of the index mechanism but
1. We can include a bunch of auxiliary steps. That pushes SoS to a
dangerous application that I do not want to encourage.
2. We can define a bunch of unnamed steps and do something like

```
[my_step_100 = pre-defines-1]
```

3. We can import a bunch of action functions, but there is nothing special
and we can do this through regular import. Users can either import sos and
decorate their functions in their own module, or do something like

```
from mymodule import func1, func2, func3

func1 = SoS_Action(func1)
func2 = SoS_Action(func2)

@SoS_Action
def func3_wrapper(parameter):
   return func3(parameter) is None

```

The advantage is that `mymodule` can be defined independent of SoS and used
in other places.

Bo

**Comment by gaow** [comment]
Oh I see here modules refer to pre-defined SoS text ... yes snakemake would call these "wrappers". I think it will make our life easier if we restrict it to actions only. One way out, as you proposed, is to encourage users to write python functions. But perhaps a lot useful actions are just `run()` calls with hard-to-remember arguments that is best imported one way or another rather than copy-paste. Perhaps we can define a special SoS action that exclusively imports a desired action from another SoS file (e.g. from given action at given step)?

**Comment by bpeng2000** [comment]
I tend to think the currently SoS is open enough.because it can run any
external script and import any python function. The SoS level import, e.g.
import SoS action function, import SoS step, and import SoS workflows are
possible but we should keep things simple for now until we find a good
justification for such features.

Bo
