### ISSUE TITLE
Support for docker

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#22]
What sure what is involved/required to support docker.

**Comment by gaow** [comment]
I think docker support is more important than cloud support.

**Comment by bpeng2000** [comment]
Docker support can mean two things: help the creation of docker and the use of docker. I think we should 

1. Try to build a docker container for a workflow, for example, a variant calling workflow, with SoS, and see how can SoS help during this process.

2. Try to use the docker to analyze data. This involves either calling SoS from the docker, or calling local SoS to execute workflow in the docker. The biggest problem here, from my limited understanding, is how to use docker software to analyze local input and intermediate files. I am not sure if cross-platform (e.g. linux docker executed on mac docker server) is an issue.

**Comment by gaow** [comment]
By Action here you mean an SoS action, not a subcommand? I'm more thinking like a subcommand that builds an SoS workflow to a docker -- that copies all required commands, libraries, and input files over to a docker container? If that's the case for 1 & 2 I agree it is what we need to have. My understanding of 3 is that you want to borrow some steps from existing docker image to use for another workflow? It seems dangerous behavior because a mixture of docker/local environments sounds somewhat confusing. Instead, can we do something like "undocker" to extract whatever we built into a docker image to local computer and let the users take their risk deciding what to adapt?

**Comment by bpeng2000** [comment]
I have read a lot here: https://github.com/KHP-Informatics/ngseasy

To answer your questions:

1. It is not possible to automatically copy all commands libraries etc to a docker image. `Dockerfile` with `docker build` is the right way to go. I have added a `docker_build` action that build docker container from specified Dockerfile. The link I gave has a lot of Dockerfiles for NGS studies.

2. The second option is for the case where the complete workflow is defined in a comprehensive container. What we do is then pull the container and run the sos script. We will need to figure out how to specify input and output files though (mount volumes etc)

3. On the contrary, I think it is quite nice to download a docker image and run its command for a SoS step. ngseasy is essentially do this. It builds containers for different tools and use them to build complete workflows. 

I need to read more and do more experiments but I believe we are good to go if we can make these three components work.

The following is CWL's docker options that we might use a runtime options

| field | type | required | description |
| ------ | ------ | ------| ---------------------------- |
|dockerPull|	string|	False	|Specify a Docker image to retrieve using docker pull.|
|dockerLoad	| string|	False	| Specify a HTTP URL from which to download a Docker image using docker load.|
|dockerFile	| string	| False | Supply the contents of a Dockerfile which will be built using docker build.|
|dockerImport	| string	| False | Provide HTTP URL to download and gunzip a Docker images using `docker import.|
|dockerImageId	| string|	False| The image id that will be used for docker run. May be a human-readable image name or the image identifier hash. May be skipped if dockerPull is specified, in which case the dockerPull image id must be used.|
|dockerOutputDirectory|	string	|False|Set the designated output directory to a specific location inside the Docker container.|

and here is cwl's docker example

example-docker.cwl
```
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: node
hints:
  - class: DockerRequirement
    dockerPull: node:slim
baseCommand: node
inputs:
  - id: src
    type: File
    inputBinding:
      position: 1
outputs: []
```
example-docker-job.json
```
{
  "src": {
    "class": "File",
    "path": "hello.js"
  }
}
```
Now invoke cwl-runner providing the tool wrapper and the input object on the command line:
```
$ cwl-runner example-docker.cwl example-docker-job.json
[job 140259721854416] /home/example$ docker run -i --volume=/home/example/hello.js:/var/lib/cwl/job369354770_examples/hello.js:ro --volume=/home/example:/var/spool/cwl:rw --volume=/tmp/tmpDLs5hm:/tmp:rw --workdir=/var/spool/cwl --read-only=true --net=none --user=1001 --rm --env=TMPDIR=/tmp node:slim node /var/lib/cwl/job369354770_examples/hello.js
Hello world!
Final process status is success
```
Notice the CWL runner has constructed a Docker command line to run the script. One of the responsibilies of the CWL runner is to the paths of input files to reflect the location where they appear inside the container. In this example, the path to the script hello.js is /home/example/hello.js outside the container but /var/lib/cwl/job369354770_examples/hello.js inside the container, as reflected in the invocation of the node command.

**Comment by gaow** [comment]
Great resource! I was just worrying about SoS not gaining enough attention because we do not have a lot established example workflows in their repository for sharing. But if for example we can make docker work, we'll be able to use resources / tech support from `ngseasy` and update our own bioinformatics framework (I boldly conclude that ngseasy is more comprehensive than VPT based NGS pipelines, if not up-to-date by looking over what it has). So practically it is very appealing.

**Comment by bpeng2000** [comment]
Just submitted a patch that adds action `docker_run`, with parameters defined in [docker run/docker-py create_container](https://docker-py.readthedocs.org/en/stable/api/#create_container) , we can even say support for docker is complete.

Basic example:

```
[0]
docker_run:  image='ubuntu'
 /bin/ls -l
```

Note that `create_container` supports parameter `working_dir` so we almost have a name conflict between runtime option and action option. We can solve this by adding `action_option={'workdir': 'somedir'}` if there is indeed an action option named `workdir`, but then we have two mechanisms of passing action options...

**Comment by bpeng2000** [comment]
runtime option `docker_image` is implemented and will make all script-calling actions in the process execute in the specified docker. There are a few problems left, the biggest one is how to handle volumes.

```
input_volume = os.path.dirname(fastq_files[0])
output_volume = os.getcwd()

run: docker_image='compbio/ngseasy-fastqc:1.0-r001', 
    docker_volumes=['${input_volume}:/input_data', '${output_volume}:/output_data']
```

works but quite tedious. Basically, the `docker_volumes` option helps

1. determines the directory of the input files (other than `input` and `depends`)
2. determines where in the docker to mount the input directory (`/var/lib/sos`? `/input_data'? `/home/some`?)
3. determine the directory of the output files (current working directory?)
4. determine where in the docker to mount the output directory ('/output_data'?)
5. there can also be resource directory etc and directory from another docker (`volume_from`)

Perhaps we need to find a more detailed CWL example to figure out how CWL does this.

**Comment by bpeng2000** [comment]
Close this ticket for discussions of specific problems in different threads.
