### ISSUE TITLE
Default sigil

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#26]
Python 3.6 introduced formated string, which uses `{}`. It also accepts expressions (with addition of conversion `!` and format specification `:`)
but so I am very attempted to declear that all SoS string literals are python format string. However, the use of `{}` forces the doubling of regular
`{` and `}`, which is disastrous for scripts such as shell and R.

I guess I will have to specify that SoS string is different and has to be configurable sigil for different languages.

**Comment by gaow** [comment]
I was not even aware python 3.6 introduced these formatting (good to know now!). I believe a lot people still use the % convention. My point is that we should perhaps not sacrifice simplicity for features less used. I can imaging people will hate to have to use `{{ }}` in R scripts ... and R savvy may not appreciate these from python and will not understand why the complications ...

**Comment by bpeng2000** [comment]
I think the Python developers chose {} because they are rarely used in
Python, but {} is really not good for other languages. I chose ${} because
most people knows it and recognizes it from shell scripts, and ${} is
rarely used in python and R, even in simple shell scripts.

I suppose we will have to use our own interpolation syntax. Having
configurable sigil can be useful and/or confusing.
