### ISSUE TITLE
Rename check_output

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#32]
The name action `check_output`  conflicts with `subprocess.check_output`. In need of a better name.

**Comment by gaow** [comment]
Perhaps `command_exists` or `cmd_exists`?

**Comment by bpeng2000** [comment]
Sorry, I meant check_output, which execute the command and check its output against pattern.

**Comment by gaow** [comment]
Then how about `compare_output`?

**Comment by bpeng2000** [comment]
Renamed for search_output because `search` is the underlying function (`re.search`).
