### ISSUE TITLE
sos dryrun mode

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#33]
We would like to encourage users to run a script in dryrun mode to check the integrity of the script and running environment (availability of command etc) before actually running a script. Currently the dryrun mode is implemented as

```bash
sos run -d script [workflow] [options]

```
We use `-d` instead of `--dryrun` because SoS allows arbitrary command line arguments to be defined by a SoS script and using `--dryrun` might cause conflict.

Since `-d` is not commonly used for dryrun mode, perhaps a dedicated `dryrun` subcommand is better?

```bash
sos dryrun script [workflow] [option]
```

We can even define both in case no method is better than another.

**Comment by gaow** [comment]
I agree with what you proposed. I'm also thinking if we "dryrun" every script by default before a real run, and we write some dry-run pass signature to `.sos` so that a future dryrun can be avoided? This is a bit ugly but may help improving user experience.

**Comment by bpeng2000** [comment]
Right now actions such as check_command are executed in both dryrun and run mode. We can switch them to dryrun mode only if we are dryrunning all scripts before formal execution. Dryrun mode should execute rapidly because NO computationally intensive steps are supposed to be done outside of SoS actions.

Dryrun mode is supposed to be an environment checking and error finding process so running the script immediately after it seems to beat the purpose. A dedicated subcommand still makes sense even if run mode includes a dryrun step.

**Comment by bpeng2000** [comment]
I just added command `sos dryrun` as an alias to `sos run -d`. We can remove it later if it is less useful than we expect now.
