### ISSUE TITLE
Allow assignment between step input and output

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#39]
In cases where `output` needs to be composed from `input`, there can be a need to process `input` or `_input` before step `output` is specified.

Right now a SoS step can have

```
assignment
step_input/output/depends
statements
```

The proposed layout would be

```
Mixture of assignment/step_input/output/depends
statements
```

Note that step `input` could introduce loop and run the assignments and step `output` and `depends` repeatedly.

**Comment by gaow** [comment]
Additionally I have a need to post-process `_output` after it is assigned. For example:

```
...
input: for_each = ['n', 'mean']
output: pattern = 'exec=rnorm.R::n=${_n}::true_mean=${_true_mean}.${output_suffix}'
_output = [get_md5(x) for x in _output]
```

You see my original file name of output is very ugly because it contains all parameters used, which can be long and arbitary. I want to then create a hash for the output name string via `_output = [get_md5(x) for x in _output]` so that I'll use the converted name set for output. This is not possible now and I believe this is best addressed with this ticket.

**Comment by bpeng2000** [comment]
I see. The problem here is that `_step.output` collects `_output` before step action take place. It is possible to do that after action but the existing implementation allows us to check step signature before process is touched. It is possible to execute process twice, first in dryrun mode to determine _step.ouput then in run mode, but it is possible the process act differently in two modes.

Another solution is to add `process:` to explicitly separate step process.

**Comment by bpeng2000** [comment]
Did you try to add an empty step `depends` or `runtime` to make `_output` part of the non-process section of step?

**Comment by gaow** [comment]
I'm not sure what that means ... adding an empty `depends: ` after `output:` ?

**Comment by bpeng2000** [comment]
Yes. SoS right now treats everything after the last directive as step
process, so adding an empty depends will make the _output line evaluated
after step output:.

**Comment by gaow** [comment]
I tried it. Somehow it does generate an output under the expected name (composed of MD5 sum) but SoS still looks for an output under the old name and thus raised an error because the output is not found. 

Here is the test script.
[1.sos.txt](https://github.com/bpeng2000/SOS/files/180877/1.sos.txt)

**Comment by bpeng2000** [comment]
pull and try again.

**Comment by gaow** [comment]
Yet the test script still fails, with / without `depends:`

**Comment by bpeng2000** [comment]
Your script put depends before _output = , right? Please put depends after
the assignment statement. Please also make sure you pull the latest version.

**Comment by gaow** [comment]
Ok that name conversions works but there is a new problem:

```
INFO: Execute DSC_10: 
INFO: _step.input: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds', '8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _step.output: ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
INFO: _step.depends: []
INFO: _idx: 0
INFO: _input: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds']
INFO: _output: ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
```

The `_step.input` got the input names right (two `*.rds`) files yet `_input` removed the 2nd file. I believe this bug was newly introduced ...

**Comment by bpeng2000** [comment]
```
INFO: Execute DSC_10: 
INFO: _step.input: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds', '8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _step.output: ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
INFO: _step.depends: []
INFO: _idx: 0
INFO: _input: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds']
INFO: _output: ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
INFO: _idx: 1
INFO: _input: ['8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _output: ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
```

two files `_step.input` are assigned to `_input` individually because of `group_by='single'`, yet your `output: pattern = 'exec=mean.R.{base}.${output_suffix}'1 depends on `base` and produced two files, twice for each `_input`, and the final output has two files.

**Comment by gaow** [comment]
I was expecting that _output matches the behavior of _input ... what should I do in this case? There is no `group_by` option for `output: `.

**Comment by bpeng2000** [comment]
What exactly is your intended behavior? Right now _step.output is composed
of_output but removes duplicates.
