### ISSUE TITLE
Default input for combined workflow

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#40]
I have a SoS script like this

```
[a_1]
[a_2]
[b_1]
[b_2]

[A_1=a_1+b_1]
[A_2=a_1+b_2]
[A_3=a_2+b_1]
[A_4=a_2+b_2]
```

I'm hoping to run workflow `A` so that all the 4 workflows will be executed. However my hope was that for example `b_1` will automatically take the output from `a_1` as its input. It does not seem to be the case in the current implementation. The INFO messages have empty input and I'm guessing this is because each element in the workflow still looks for its upstream by index, rather by their new position in the combined workflow. Is that the case and how do I achieve my goal, then?

**Comment by gaow** [comment]
I should say that I can easily change implementation on my end to bypass the "bug" (or "feature") so it is not exactly an issue for me. I'm just rising the question here for us to consider if this behavior is welcomed and if we want to change it.

**Comment by bpeng2000** [comment]
This is a bug that should have been fixed. The problem was that the global process was also involved in the output of previous step becomes input of this step magic.
