### ISSUE TITLE
Error with `group_by='pairs'`

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#42]
I have this script:

```
input_files = ('1.txt', '2.txt', '3.txt', '4.txt', '5.txt', '6.txt', '7.txt', '8.txt')

[1]
for item in input_files:
    run('touch ${item}')

[2]
output_suffix = 'out'
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
output: pattern = '{_base}.${output_suffix}'
run('''
echo ${_input}
echo ${_output}
''')
```

and I got this error message 

```
ERROR: Failed to process directive input: 'NoneType' object is not iterable
```

Please pull and reinstall sos for a minor bug fix before trying to reproduce the error. Thank you!

**Comment by bpeng2000** [comment]
This option was not tested. Please check now.

**Comment by bpeng2000** [comment]
Note that this option is called `paired` in the code and perhaps `pairs` in the documentation. Not sure which one is better.

**Comment by gaow** [comment]
Great! I do think `pairs` is good.
