### ISSUE TITLE
Support only python 3

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#45]
Python 3 contains modules such as concurrent and asyncio which can be useful for SoS. These modules are not available for Python 2.7 so it makes sense to support only Python 3.x.

**Comment by gaow** [comment]
I agree! Nowadays I try to stick to Python 3 for all my work. Also the thought we had in the "version" of SoS script the `1.0py2` -- should we still allow for something like this or we have to force users to program in Python 3, particularly now that an SoS action can look like free code in the new syntax?

**Comment by bpeng2000** [comment]
Ok, let us switch to avoid trouble in handling different versions of SoS script. Python 3 code is not that different so as long as users stay with basic python syntax, there can still write in Python 2 syntax.

**Comment by bpeng2000** [comment]
Done. Python 2 support has been removed from SoS.
