### ISSUE TITLE
Step process made prettier

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#47]
Current SoS steps look more or less like this

```
[*_31]
# get the number of mapped reads
input: sortbam.output, group_by='single'
output: '${_input}.bai', '${_input}.flagstat'
process:  concurrent=False

run('''
samtools index ${_input}
samtools flagstat ${_input} > ${_input}.flagstat
''')
```

and I am wondering if we can write it as

```
[*_31]
# get the number of mapped reads
input:     sortbam.output, group_by='single'
output:    '${_input}.bai', '${_input}.flagstat'
run:       concurrent=False

       samtools index ${_input}
       samtools flagstat ${_input} > ${_input}.flagstat
```

where `run` etc can be any SoS action that accepts a single string input, and we can add multiple sections if needed (e.g. `run:`, `python:`)

Pros:

1. Make SoS scripts easier to read
2. Remove most of the triple quotes and actually allows scripts with triple quotes
3. Automatic dedent (remove common leading spaces) allows the use of `[XX]` etc in script. 

Cons:

1. The current logic of `process` will start a new process and `run()` etc can be inline (executed with SoS) or external (separate process) need to be changed. We can keep the `run()` form inline though.

2. Python syntax highlighting will fail if we include blocks of, e.g., R code in this way. But we previous do not have syntax highlighting for R code anyway.

3. More rules to remember

**Comment by bpeng2000** [comment]
Liked the new syntax a lot so I implemented it. We can revert the changes if it does not work out.

**Comment by gaow** [comment]
Indeed it is prettier. Will test it out and raise problems if there is any!

**Comment by bpeng2000** [comment]
It is a parser trick to convert 

```
action: option
   text
```

to 

```
process: option
action('''text''')
```

with automatic dedent of `text`. The difficult part was we might see things like `else:` in python code but it should work now after I disallow all Python keyword as action names.
