### ISSUE TITLE
Disallow changing _output directly

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#51]
There is a need to modify `_output` and a proposal to implement something like a `filter=func` option. The reason is that the outcome of `pattern` needs to be post-processed. However, for this special case, pbecause `pattern` is simple to simulate, perhaps

```
[func('${} ${}' for x, y in zip(_A, _B)]
```

is enough for

```
pattern='{_A} {_B}', filter=func
```

so we do not need a separate output option.

The real trouble behind changing `_output` directly is we will have to monitor each statement for the change of `_output` and even so change of `_output` might not affect `_step.output` because statements after `process` might be executed in a separate process. Even worse is that we might evaluate statement multiple times (e.g. dryrun before run) so `_output = process(_output)` can fail.

**Comment by gaow** [comment]
I noticed that currently modifying `_output` directly will trigger an error message but `filter` option is yet to be implemented. Is this the case?

**Comment by bpeng2000** [comment]
Yes. I submitted another ticket for this, basically I argued that the `pattern` output option is very easy to simulate so we do not really need an additional option for this special case. Something like

```
output: [myfunc('${x} ${y}.txt' for x,y in zip(_B, _C)]
```
should suffice.

**Comment by gaow** [comment]
Yes, it now does look like we do not need an additional keyword option like `filter` and we can even remove `pattern`. I'm just not sure if there are scenarios where this is not sufficient but I cannot think of any for now.

**Comment by bpeng2000** [comment]
I think `pattern` is useful as a matching option for input `pattern` especially for people from the snakemake camp. I just cannot justify another arbitrarily powerful option. I mean, if people have to learn a complex option to manipulate outcome of `pattern`, it would be easier just use python.

**Comment by gaow** [comment]
What is the current syntax for output name post-processing now that modifying `_output` is disallowed? I was trying to change my script to
```
output: get_md5('exec=rnorm.R::n=${_n}::true_mean=${_true_mean}.${output_suffix}')
```
Where the input of the get_md5 function is a list of strings. It does not work for now so I'm not sure if we are currently with the `pattern` + `filter` idea or how do we "just use python" in this case.

**Comment by bpeng2000** [comment]
You will need to first get a list of strings if `get_md5

**Comment by bpeng2000** [comment]
The Python 3 list comprehensive + SoS interpolation bug is now fixed. I suppose we can expose the output pattern matching function if this can help you post-process the `pattern=` result.

**Comment by gaow** [comment]
Great! But still I cannot get it work: 

```
ERROR: Failed to process step output: get_md5(['exec=rnorm.R::n=${x}::true_mean=${y}.${output_suffix}' for x, y in zip(_n, _true_mean)]) (zip argument #1 must support iteration)
```

My understanding is that `_n` is a single integer not a list, so this syntax will not work.

**Comment by gaow** [comment]
The complete test script is here:

[1.sos.txt](https://github.com/bpeng2000/SOS/files/190972/1.sos.txt)

**Comment by bpeng2000** [comment]
I have exposed functions `extract_pattern` and `expand_pattern`. The latter should help you simplify the code. Something like

```
output: get_md5(expand_pattern('exec=rnorm.R::n={_n}::true_mean={_true_mean}.${output_suffix}'))
```

**Comment by gaow** [comment]
Great it works! But there is yet another problem with input/output matching for which I'll open another ticket
