### ISSUE TITLE
A shared step option.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#52]
Right now all SoS steps are executed in separate processes and the only return value is the step info specified by the `alias` option. There are two problems:

1. A step might want to return more values. For example, a step might return a flag that directs later steps.

2. Although a SoS step returns only an alias, it can make use of all variables defined up to the current step. This is not a problem for now because a step cannot rely on other steps if other steps only returns step into (alias). However, we might need to specify what other variable it relies on it problem 1 is addressed.

Proposal:

Add a `shared` step option to specify which variable a step will use (if available) and return. Steps that share the same variables will form a dependency relationship.

**Comment by gaow** [comment]
So the script will look like:

```
[1: shared = a, b, c]
a= ...
b= ...
c= ...
d = ...
```
right? and if a variable is not `shared` (`d` here) then it should not be accessible from any other step? I'm cool with the syntax. An alternative might be (C++ style):

```
[1]
a = ..
b = ..
c = ..
private:
  d = ...
```
so by default variables are all to be shared unless otherwise said.

**Comment by bpeng2000** [comment]
This is to further ensure that steps are independent (and can be executed in parallel). Right now, all step variables are private except those in global and parameters section. More specifically,

1. Global definitions are available to all, and are readonly
2. Parameters are available to all, and are readonly
3. Only aliases can be sent back from step.

That is to say,

```
[10]
a=10

[20]
b=a+1
```
would fail.

The first question is if there is a need to return a variable from step. Everything can of course be achieved using files but sharing of variables can be easier. We however need a strong case for the addition of complexity.

Then if there is a need to return additional variables, there might be need to specify variables to use.The problem is actually larger than it looks. For example,

```
[10]
input: some_step.output

run:

another_step.output

```

relies on `some_step.output`, which we can detect from `input`, but it also depends on `another_step`, which we can not detect until runtime. This is why I asked if we should expand `depends` to depend on another variable (or expression), or use `shared` to declare this, and other the use of other variables produced from other steps.

**Comment by gaow** [comment]
Let me try to clarify: currently `depends:`  only work on files not variables, and we want to expand `depends:` to also work on variables from other steps which have to be available in global name space due to some tagging, e.g., step option `shared`?

**Comment by bpeng2000** [comment]
The problem is that the step might depend on other variables in addition to file dependencies. `shared` is not a good name for the example I gave but I do not know how to expand `depends:`.

**Comment by gaow** [comment]
like `depends: files = ..., variables = ...`? And again these variables have to be in global one way or another. As for name, how about `public`? `alias` would automatically be "shared" or "public", though.

**Comment by bpeng2000** [comment]
On a second thought, we do parse all statements and look for raw strings to interpolate, and we can of course look in a step and check the use of variables, and make such dependency check automatic. So let us worry about such implicit dependencies when we really start building the DAG.

The `public` or `shared` option sounds useful. Implementation wise it is very easy because the mechanism is already in place, but let us also see if we can find a good justification for this feature.

**Comment by bpeng2000** [comment]
Another possibility is to expand `alias` so that `alias='aligned'` will create a variable `aligned` with ALL variables defined in a step (e.g. variables created by `pattern` etc). Users can simply do

```
[10: alias='aligned']

result = 'success'

[11]
if aligned.result == 'success':
  do something
```

The problem is that

1. `result` will not be available if it is defined in step process (and executed in a separate process). In theory there can be multiple copies of `result` due to input loop so we cannot return a single value anyway.
2. This does not allow real sharing of variables because `aligned.result` is readonly. This does not have to be a disadvantage though.

**Comment by gaow** [comment]
This is essentially making all variables public yet under specified "namespace" (`alias`). For the read-only problem, if we want to modify the values it is natural to do in step `xx`: `result = foo(aligned.result)` and the following step can access both versions of result `xx.result` and `aligned.result`, which is even more transparent.

**Comment by bpeng2000** [comment]
As long as the variables are readonly so that use of `aligned.result` in `step_10` does not affect the use of the same variable in `step_20`, I do not mind exposing more variables using `alias`. Again, this excludes the use of `global variables` that can be written by any step but such variables are nightmare to deal with for parallelization and should not be used anyway. I will implement this feature.
