### ISSUE TITLE
Expand arbitrary variable to construct output file names 

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#54]
This is related to Issue #53. My solution is to keep trying massaging `base` before feeding into the md5 calculation. I want to implement the following:

```
[mse_1: alias = 'mse']
output_suffix = 'rds'
input_files = get_input_sos((estimate.output, simulate.output))
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
paired_names = ['{}_{}'.format(x,y) for x, y in zip(base[:int(len(base)/2)], base[int(len(base)/2):])]
output: get_md5_sos(expand_pattern('exec=MSE.R.${paired_names}.${output_suffix}'))
```
Where I want to expand the `paired_names` variable to get output names. Currently it does not work since there is no `pattern` to expand and by default `${}` is treated a string. Since we already have `expand_pattern` function, is it possible to generate it to also capable of expanding a variable if the input is a list? Perhaps the case when there are both patterns and list variables should be considered ... something like `${_paired_names}` to indicate looping on patterns of variables seems a good shortcut but we never have used `_` for cases such as this one.

**Comment by bpeng2000** [comment]
Why do you need to manually split `base` when `_base` is already paired with each `_input`?

**Comment by gaow** [comment]
By "manually split base" you refer to `zip(base[:int(len(base)/2)], base[int(len(base)/2):])`? I tried `paired_names = ['_'.join(x) for x in base]` assuming each x is a pair of base names of input, but it does not work.

**Comment by gaow** [comment]
```
input = ['a.txt', 'b.txt', 'c.txt', 'd.txt']
base=['a', 'b', 'c', 'd']
paired_names = ['a_b', 'c_d']
_input = ['a.txt', 'b.txt']
_paired_names = ['a_b']
_output = get_md5(_paired_names) + '.txt'
_step.output = [get_md5('a_b') + '.txt', get_md5('c_d') + '.txt']
```

Because `_base` will match with `_input` in pairs, I need to consolidate it into `paired_names` before expanding in `output`. Otherwise I will get 4 output instead of 2 in this mock example.

**Comment by bpeng2000** [comment]
First, `pairs` groups input by `['a.txt', 'c.txt']`, second

```
input = ['a.txt', 'b.txt', 'c.txt', 'd.txt']
base=['a', 'b', 'c', 'd']
_base=['a', 'c']
_input = ['a.txt', 'c.txt']
_output = get_md5('_'.join(_base)) + '.txt'
_step.output = [get_md5('a_c') + '.txt', get_md5('b_d') + '.txt']
```

so there is no need for `paired_names`

**Comment by gaow** [comment]
Yes, I see it should be `ac`, `bd`. I've tried to use what you proposed but it does not work for this specific example, thus I was trying to introduce `paired_names` instead. What I previously had was:

```
output: get_md5('exec=MSE.R.{}.${{output_suffix}}'.format('_'.join(_base)))
```

which gives an error message:  (local variable 'value' referenced before assignment)

But looking at it again, it seems an error in the Python code of SoS, not necessarily that the approach does not work ...

**Comment by bpeng2000** [comment]
without the `getmd5` part, 

```
output: 'exec=MSE.R.${",".join(_base)}.${output_suffix}'
```

yields

```
 'exec=MSE.R.8e595e2a1634ae5d0b0a2dff6a0bba88,352d5e05ef793b7eac5d58f18baa2aad.rds'
```

so `",".join(_base)` is working.

**Comment by bpeng2000** [comment]
Note that

```
'exec=MSE.R.{}.${{output_suffix}}'.format(','.join(_base))
```

is the same as

```
'exec=MSE.R.{}.${output_suffix}'.format(','.join(_base))
```

because

```
'exec=MSE.R.{}.${{output_suffix}}'
```

is executed before `.format`, and you `{output_suffix}` is interpreted as a set.

**Comment by gaow** [comment]
Oh thank you it works -- false alarm due to a coding error on my end. I was just not confident on the syntax so I looked away when I hit an error message :) 

I guess we can close this ticket for now and worry about it when we really need to compose output file names from a step variable which does not belong to any element in input (i.e., patterns, for_each and paired_with). I think that'll be a rare case if ever happens.
