### ISSUE TITLE
Rename _step.input to input, _step.output to output

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#55]
If we name

* `input`: all input filenames, currently `_step.input`
* `output`: all output filenames, currently `_step.output`

we keep 
* `_input`: loop input, subset of `input`
* `_output`: loop output, subset of `output`

So that

1. All 'complete' names (from `pattern` etc) refer to complete input/output files
2. All `_name` refer to loop/partial variables.
3. We do not have to create `_step.input` etc. The aliased name `aligned.input` also comes natural because it refers to `input` of the step with alias `aligned`.
4. For beginners they can use `input`, `output`, which is a bit more intuitive than `_input` and `_output`.

The downside is that we effectively disallow the use of `--input` command line option unless we change the `parameters` mechanism a bit.

**Comment by gaow** [comment]
I am in favor of the changes because `_step` was the only exception that `_` is not for loop variables. Now we are unified and `input` `output` is a lot like snakemake syntax which makes it easier to understand for new comers.

**Comment by bpeng2000** [comment]
Changes made. This makes `input:`, `output:`, `depends:` generates variables `input`, `output`, and `depends` respective, which is more intuitive.
