### ISSUE TITLE
!r and !s string conversion

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#56]
The current implementation applies `!r` and `!s` to each item of an iterable object so

```
'${['a', 'b', 'b'] !r}`
```

reproduces 

```
'a' 'b' 'c'
```

and

```
'${['a', 'b', 'b'] !s}`
```

reproduces 

```
a b c
```

Given that !r means `repr(obj)`, I am wondering if we should keep its original meaning and return the complete representation of the object, e.g.

```
['a', 'b', 'c']
```

Or, we can at last save `!s` (string representation) for such purposes.

Currently in python

```
>>> '{!r}'.format(['a', 'b', 'c'])
"['a', 'b', 'c']"
>>> '{!s}'.format(['a', 'b', 'c'])
"['a', 'b', 'c']"
>>> '{!s}'.format('a')
'a'
>>> '{!r}'.format('a')
"'a'"
>>> '{!r}'.format({'a'})
"{'a'}"
>>> '{!s}'.format({'a'})
"{'a'}"
```

`!r` and `!s` seems to be different only for single strings.

**Comment by bpeng2000** [comment]
Note that complete `repr` or `str` can always be achieved with

```
${repr(obj)}
```

and

```
${str(obj)}
```

I am just not sure if it is a good rule to apply all conversion flags to individual items.

**Comment by gaow** [comment]
It looks from your example that !s is basically useless ... we have talked about it a while ago. If there is a need for repr() on a list it is good idea to re-purpose. But I'm neutral to it because as you pointed out it is not hard for users to construct it when necessary (as long as it is documented in the wiki).

**Comment by bpeng2000** [comment]
The Python 3.6 format string guys also argued that `!r` and `!s` are not helpful because of direct use of `repr`. SoS goes a step further to apply it to items of an object, which makes them more useful. I guess I will stick to the current syntax and explain the use of `repr` in the wiki.
