### ISSUE TITLE
json or ini based configuration file.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#65]
`argparse` allows  `fromfile_prefix_chars`, with which we can allow users to input a large number of default values using format like

```
sos run script @config.txt
```

where `config.txt` just list arguments line by line.

We can also define functions such as

```
config('config_file', 'key', type=None)
```

where

`config_file` is a configuration file,
`key` is something like `key` or `section.key`
`type` can be `json` and/or `ini` or something else

This function can be used like

```
[parameters]
config_file = 'myconfig.ini'

# sample name
sample_name = config(config_file, 'design.samples')

# number of cases
cases = config(config_file, 'design.cases')
```
and users can provide default values to many parameters using `--config_file myconfig.ini`.

I am not sure if we should provide a way to **insert** a large number of definitions, similar to

```
exec_file('myconfig.py')
```

For this particular case, perhaps it is easier to provide a dedicated option such as

```
-c       A configuration file whose values will be inserted to the 
         script as if they are defined and provided from the parameters section
```

**Comment by bpeng2000** [comment]
I just submitted a patch for a `-c` option that accepts YAML/JSON based configuration file. JSON is a subset of YAML so pyyaml should be able to parse JSON based config file. I chose YAML/JSON because 

* values in `ini` (python `configparse`)  are all strings and we might need other types (int, float etc).
* using `.py` as configuration file is too dangerous because arbitrary statements would be allowed.

Right now the `-c` option sets SoS variable `CONFIG` so items such as

```
CONFIG['username']
```

could be used in the script after `-c config_file`.

Note that users can override config values from command line like

```
[parameters]
# sample name
sample_name = CONFIG['sample_name']

# number of cases
cases = CONFIG['cases']
```

although `CONFIG['cases']` should not be changed.

Pending issues:

1. Is `CONFIG` a good variable name?
2. Do we need other config mechanism?

**Comment by gaow** [comment]
I was under the impress we want to avoid configuration files. `snakemake` uses YAML based configuration and syntax like `--config A=B, C=D` to assign value from command line if only minor changes are involved. I liked the fact that an SoS script is self-contained and we never need to have multiple files for one workflow (That's a big advantage we had nested workflow and subworkflow). It seems configuration file undermined our efforts.

How about we replace configuration file with a configuration section in SoS? The section should still be written in JSON or YAML for example `[configuration, format = 'YAML']`. Then we also allow for command line such as  `-c A=B, C=D` if anything needs to be changed, but we have to remember the data type YAML tells us and convert it accordingly, that is to say we should properly convert for list, tuple and dict -- perhaps we can rely on YAML for that as well by parsing to it a `StringIO` stream.

**Comment by gaow** [comment]
Or, we can merge parameter section with configuration section and force use JSON / YAML format

**Comment by bpeng2000** [comment]
The value of config file is, in my cases, that I do not need to hard-code environment specific variables (such as name of computing node, command to submit job, user name and password to mysql server) or specify them over and over again from command line. We can even read a `~/.sos/config.yaml` and allow users to specify such kind of stuff without `-c option`.

I am against the idea of writing `parameters` in YAML because we should have only Python syntax in SoS script. Right now `-c` provides a readonly `CONFIG` variable that does not affect scripts that do not use config file.

**Comment by bpeng2000** [comment]
Another option is to use variables defined in config file as variables defined in the global section of the SoS script, free users from the `CONFIG['key']` trouble. 

Pros:

1. Convenience. For example,

```
gatk_path = 'a default path'
```

can be silently re-defined by `gatk_path` in configuration file. There are no separate `gatk_path` and `CONFIG['gatk_path']` to deal with.

With the existing implementation

```
gatk_path = CONFIG['gatk_path']
```
would require a configuration file with this key, although users can do

```
gatk_path = CONFIG.get('gatk_path', 'a default path')
```

Cons:

1. Readers are not sure what are defined in configuration files and arbitrary variables can be inserted and make them wonder where some variables are defined. In contrast, the existing implementation makes clear that `CONFIG['key']` are defined in configuration file.

**Comment by gaow** [comment]
I find `CONFIG` agreeable compared to potential confusion otherwise. Syntaxwise, can we use something like `CONFIG.key` which is easier to write?

**Comment by bpeng2000** [comment]
Ok, this has been implemented. The only problem I can see with `CONFIG.key` (other than having two methods to access the same data) is that it will make `CONFIG.get(key, default)` a bit strange to use.

Please update doc for this change.

**Comment by gaow** [comment]
Is `.get` the only action `CONFIG` has? what if we make it a `_call_` and use `CONFIG(key, default)` instead?

**Comment by bpeng2000** [comment]
Because of the readonly nature of `CONFIG`, most dictionary actions do not apply here so `get` is about the only function that is useful. However, `CONFIG(key, default)` introduced the third method to access `key` (`CONFIG('key')`, `CONFIG['key']` and `CONFIG.key`) and should really be avoided.

**Comment by gaow** [comment]
I was thinking we disallow `CONFIG['key']` and use `CONFIG('key')` or `CONFIG('key', default)`. The dot syntax looks a lot neater. I just worry if someone sets a parameter `get` then `CONFIG.get` will fail. And I do not think people have to be attached to `CONFIG['key']` the dict type of syntax because they do not have to assume `CONFIG` is a dictionary. 

I'm also cool with the current status if somehow `CONFIG.get` can work. I've updated the documentation.

**Comment by bpeng2000** [comment]
The use of `CONFIG` variable instead of automatic replacement of variables in SoS script is safer and has less surprise. Let us keep it this way for now.
