### ISSUE TITLE
docker_image in dryrun mode.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#67]
I am wondering what we should do with runtime option `docker_image` in `dryrun` mode. 

1. Download image if not available.
2. Warn that the image is not available
3. Do nothing.

**Comment by gaow** [comment]
I'd vote for a warning.

**Comment by bpeng2000** [comment]
Perhaps we can have another runmode?

1. `dryrun` mode for syntax and environment checking that does not run anything (in theory) and does not change any existing environment.

2. `prepare` mode for prepare environment such as download resources, download docker image, check input file etc.

3. `run` mode to actually perform the analysis.

**Comment by gaow** [comment]
Exactly. We can have these 3 `env.run_mode` although I'm wondering on the interface we can have something called `--level` to control for the level of the testing run: '1' for check syntax only, '2' for check environment, etc, so that we do not have another subcommand.

**Comment by bpeng2000** [comment]
We can have both, such as `-d` option and `dryrun` subcommand, because

```
sos prepare script.sos
```

is easier to read than

```
sos run script.sos -l 1
```

But on the other hand we do need `-d` or `-l 1` because

````
sos-runner script.sos
```
or
```
script.sos
```
need someway to run in dryrun and prepare mode.

**Comment by bpeng2000** [comment]
I am wondering if `argparse` accepts

```
sos run script.sos -dryrun
```

and 

```
sos run script.sos -prepare
```

(Note the single dash) because we force the use of `--` for user specified parameters.

**Comment by gaow** [comment]
I never have seen that .. but worse case is we parse from `unknown_args`

**Comment by bpeng2000** [comment]
I do not want to do anything unconventional so let us keep it as is. `-d` is not that difficult to remember, but `-l 1` would be. I suppose we can do

```
-r  run default
-d  dryrun mode
-p  prepare mode
```
so impatient users can run

```
sos run script -dpr
```
and run the script in three mode, but stop at dryrun or prepare mode if error happens. :-)

Another option is

```
-m run | dryrun | prepare
```
which is more verbose but more readable than before.

**Comment by gaow** [comment]
Do you envision many more options to be added to the command interface? If not then `-dpr` looks good idea because often we are the impatient users ourselves.

**Comment by bpeng2000** [comment]
It was almost a joke and you liked it. :-)

Let me add the prepare mode and we will see what works best. It is indeed related to what other options we plan to add later.

**Comment by gaow** [comment]
Things like `-dpr` is perhaps why argparse does not support single dash. It is also vivid because it's like abbreviation of depress (well we probably want to change -f to -s) which is what impatience often leads to :)

**Comment by bpeng2000** [comment]
Here is the part of the output from `sos run -h`, hopefully this explains the options well

```
Run mode options:
  SoS scripts are default executed in run mode where all steps are executed.
  If one or more of the runmode options are specified (e.g. '-d' or '-dpr'),
  SoS will execute the script in dryrun mode, preparation mode, and run mode
  if respective options are specified, but will stop if any error occur at
  one mode. This allows you to detect problems and download resources before
  running a script in full power.

  -d                    Execute the workflow in dryrun mode in which step
                        processes are executed normally but with most SoS
                        actions return directly. SoS also produces diagnoistic
                        warning messages in this mode.
  -p                    Execute the workflow in preparation mode in which SoS
                        prepare the execution of workflow by, for example,
                        download required resources and docker images.
  -r                    Execute the workflow in run mode in which all SoS
                        steps will be executed.
  -f                    Execute the workflow in a special run mode that
                        ignores saved runtime signatures and re-execute all
                        the steps. This option overrides '-r' if both are
                        specified.
```

**Comment by gaow** [comment]
Looks good! Hopefully the interface gets no more complicated.

**Comment by bpeng2000** [comment]
Solved with the proposed interface.
