### ISSUE TITLE
CWL/Bioconductor

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#68]
http://master.bioconductor.org/packages/3.3/bioc/vignettes/sevenbridges/inst/doc/bioc-workflow.html

Have not read it in detail. Might be helpful.

**Comment by gaow** [comment]
A simple text configuration and a core function: looks good for people who have to stick to R, but SoS is way more powerful :)

**Comment by bpeng2000** [comment]
I was interested because I rarely see examples of CWL...
