### ISSUE TITLE
conditional steps.

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#69]
There can be cases where we need to run certain steps or alternative steps according to user input. For example, in

```
[parameters]
aligner = 'bwa'
```

user might want to use a different aligner, which would force the use of some steps or complete alternative nested workflows, something like

```
[bwa_1]
[bwa_2]
[novaalign_1]
[novaalign_2]
```
and we essentially need something like

```
master = quality_check + (bwa if aligner='bwa' else novaalign) + call
```

**Comment by bpeng2000** [comment]
Note that we are not trying to replace bash or python here so we do not want to introduce something very fancy. So perhaps the following can already achieve this:

```
[bwa_1: skip=aligner!='bwa']
[bwa_2: skip=aligner!='bwa']
[novaalign_1: skip=aligner!='novaalign']
[novaalign_2: skip=aligner!='novaalign']
```

or

```
[align0=bwa: skip=aligner!='bwa']
[align1=novaalign: skip=aligner!='novaalign']
```

unless we really want something like

```
[align=bwa if aligner=='bwa' else novaalign]
```

because of input/output issues. Note that currently nested workflow is implemented by name matching that does not allow python expression, I mean

```
[default = align + call]
```

is parsed at parsing time. We can potentially improve the flexibility by using expressions

```
[default = 'align + call']
```
which can then be able to accommodate things like 
```
[default = '${aligner} + call']
```

**Comment by bpeng2000** [comment]
Now that we are using real python expression,

```
[default = '${aligner} + call']
```

it makes sense to keep the step names separate from subworkflow and use syntax

```
[default: call='${aligner} + call']
```

The option can be called `nested`, `call`, `run`. We can also explicitly call the nested workflow using something like

```
[default]

exec('${aligner} + call')
```

The last syntax has the advantage that it is very clear that we are executing a nested workflow

```
[default]

input: for_each='a'
process:
action()
exec('${aligner} + call', source='another_script.sos')
```

I mean, the current syntax is good for

```
[default=call + align]
```
but not for cases when the nested workflow would be executed after some other statements.

The downside of the last syntax is that `sos show` will not know the nested workflow and cannot display their information, which is more or less acceptable.

**Comment by bpeng2000** [comment]
Solved by an enhanced version of nested workflow.

**Comment by gaow** [comment]
I'm trying to utilize this new syntax, e.g.:

```
[default]
for simulator in simulators:
    sos_run('${simulator} + analyze')
sos_run('report')
```
But it does not work. I might be violating some obvious SoS rules, although it seemed tempting to write like that ... 

```
ERROR: Failed to process statement for simulator in simulators:
    sos_run('${simulator} + analyze')
sos_run('report')
: '__execute_errors__'
```

**Comment by gaow** [comment]
In fact it looks like the trunk is broken ... not exactly that this syntax does not work.

**Comment by bpeng2000** [comment]
Sorry, I was no a laptop and could not run the test suite before I commit. I am still fixing the tests but the code should work now.

**Comment by bpeng2000** [comment]
All tests pass now. I will try to run tests before I push later.

**Comment by gaow** [comment]
Great yes it works! No worries one can always stick to an earlier commit if
the master breaks. We may consider use test branch after release 1.0

**Comment by bpeng2000** [comment]
The tests take just a few minutes to run if all docker images are downloaded, but it does need docker to run all the tests. I think I can have a flag to turn off docker related tests so that I can run the test suite on laptops.

**Comment by bpeng2000** [comment]
Ok, the test suite can now skip docker related tests...
