### ISSUE TITLE
A table for terminology in wiki

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#7]
It might worth compiling a wiki table of terms in SoS wiki that explains in brief various jargon such as "step variables", "step derivatives" , after we are somewhat more settled later.

**Comment by bpeng2000** [comment]
I do not have good names yet. We should decide on some proper names later
(but soon).

Bo

**Comment by bpeng2000** [comment]
We should borrow names from CWL or snakemake.

Bo

**Comment by gaow** [comment]
Is it current being address on the "Example" page in the form of a feature list?

**Comment by bpeng2000** [comment]
Yes, it is a combination of faq and feature list. The idea is that I will
start using SoS in my work and move some examples to that page (or the
folder if the example is long), summarize features used under the example,
and link the features to the feature list and format specification.

Bo

**Comment by gaow** [comment]
That page would be good for annotated examples. I was thinking of similar things but more organized: how about we setup an "Examples" directory or some other names and write up a sos script that automatically compiles whatever other sos scripts in it to an `*.md` file: basically parse the global comment block out and wrap a ```'''python'''``` to the file to produce something like:

Page Title
Description of this script ... whatever comments

```python
The entire sos script
```

In that way we can share a lot of real world applications that others can grab and adapt.

**Comment by gaow** [comment]
and then the feature list can be maintained under the "Documentation" folder as a stand-alone file.

**Comment by bpeng2000** [comment]
Perhaps there can be an easy way to embed the script? Right now
https://github.com/bpeng2000/SOS/wiki/Examples has a link to a plan text
file without syntax highlighting.

**Comment by gaow** [comment]
A link would be good now for the purpose of that page and for publishing whatever we have! 

I was more thinking along the lines of building a mechanism to allow an arbitrary user to be able to upload their sos script. But we can expect that to happen much later.

**Comment by bpeng2000** [comment]
Copy and paste is not that hard when we try to present the examples, say,
in pieces with a link to complete script. Let us keep it this way for now.

Good night,
Bo

**Comment by bpeng2000** [comment]
input: etc in smakemake called rule parameter, in cwl "input of a workflow step"

**Comment by bpeng2000** [comment]
I have added a terminology section to the format spec and used them in the document.

**Comment by bpeng2000** [comment]
Terminology added to spec. Let me know if they make sense to you.

**Comment by gaow** [comment]
It is very clear to me. The form of a list (rather than a table) makes me wonder of a summary like this

* Script
  * Workflow
    * Step
      * Step options
      * Step Input / output / dependencies / runtime options
      * Step process
        * Action

Not sure if it displays properly on email but basically it is an indented list that lays out the structure of a SoS file.

**Comment by bpeng2000** [comment]
I do not think it would look good but you can try.

**Comment by gaow** [comment]
Looks ugly ... the list is not long so we should be good.
