### ISSUE TITLE
Failure to determine subworkflow pattern

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#73]
I'm sure it works yesterday, but not any more:

```
[simulate]
print(1)
[analyze]
print(2)
[report]
print(3)
[default=simulate+analyze+report]
```
Error trace:
```
  File "/home/shared/miniconda3/lib/python3.5/site-packages/sos-0.5.6-py3.5.egg/pysos/sos_script.py", line 1830, in sos_run
    workflow = script.workflow(args.workflow, args=workflow_args)
Traceback (most recent call last):
  File "/home/shared/miniconda3/lib/python3.5/site-packages/sos-0.5.6-py3.5.egg/pysos/sos_script.py", line 1705, in workflow
    subworkflow = SoS_eval(section.names[i][2])
  File "/home/shared/miniconda3/lib/python3.5/site-packages/sos-0.5.6-py3.5.egg/pysos/utils.py", line 734, in SoS_eval
    return eval(expr, env.sos_dict._dict)
  File "<string>", line 1, in <module>
NameError: name 'simulate' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shared/miniconda3/lib/python3.5/site-packages/sos-0.5.6-py3.5.egg/pysos/sos_script.py", line 1830, in sos_run
    workflow = script.workflow(args.workflow, args=workflow_args)
  File "/home/shared/miniconda3/lib/python3.5/site-packages/sos-0.5.6-py3.5.egg/pysos/sos_script.py", line 1707, in workflow
    raise RuntimeError('Failed to determine subworkflow pattern from expression {}'.format(section.names[i][2]))
RuntimeError: Failed to determine subworkflow pattern from expression simulate+analyze+report
ERROR: Failed to determine subworkflow pattern from expression simulate+analyze+report
```

**Comment by bpeng2000** [comment]
Nested workflow is being reimplemented and is moving from a first-class citizen (sos syntax) to a sos action.

```
[default=simulate+analyze+report]
```

should now be

```
[default]
sos_run('simulate+analyze+report')
```
I just submitted a patch although I am still fixing the tests.

**Comment by gaow** [comment]
So this change is the solution to alternative workflow steps?

**Comment by bpeng2000** [comment]
There are several reasons:

* This allows alternative workflow, namely logics such as

```
[default]
sos_run('${aligner} + ${caller}')
```

* This make it much clearer how nested workflows will be executed. Previous we have

```
[default=wf]
input: for_each='something'
```

with empty step process (confusing). currently we have

```
[default]
input: for_each='something'
sos_run('wf')
```

* This makes the header much easier to parse. It was not a big deal with `A=B+C`, a bit more difficult for `A='${aligner}+${caller}'` and much harder for `A='bwa' if func(blah) else 'novaalign'`. If parsing that is not a problem, running `func(blah)` during parsing is a problem, and having the header this long is a bigger problem.

**Comment by gaow** [comment]
Yes, it is more flexible and clearer. the `source = another.sos` is related to the modularization we discussed yesterday which I think is good to have too, now that the syntax is more flexible. But for that to happen should we have a dedicated function for this so that the `source` option can be passed to it?

**Comment by bpeng2000** [comment]
`source` is now an option to the `sos_run` function.

**Comment by bpeng2000** [comment]
I will update the doc and the slides.
