### ISSUE TITLE
Utilize runtime signature when no output is specified

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#80]
This is a concern raised by a colleague: as we claim that SoS is input driven rather than output driven, it was natural to assume that runtime signature will work when no output is specified. In one step in his script, only input file names and command parameters are given. In two repeated runs he expected this step be skipped. However it was not the case -- SoS runs it anyways because there was no "existing output" to reuse.

For this case what I'd do in snakemake is to fake an output and `touch` it. This would be awkward to do it in SoS, because exactly we claim to be input driven which is a good feature compared to snakemake. If when output is not defined then we check only the runtime signature for the input and the command (which naturally will carry input names and parameters) -- is that sufficient to let SoS skip a step?

**Comment by bpeng2000** [comment]
You have a point here. The logic of existing behavior is that we do not require users to specify `output`, thus allowing unknown output, and cannot record signature of the step. However, if the user specifies `output: []`, we should be able to record runtime signature. 

Whether or not we should record signature for `output: unknown` is another matter.

**Comment by bpeng2000** [comment]
I have enabled this feature. Note that

1. We now have None as undefined/unknown input or output, in addition to known but empty input or output, which is specified by `input: []` or `output: []`.

2. Unknown output will be taken by the next step as unknown input.

3. We do not have runtime signature for steps with unknown input or output, but we now have signature for steps with empty input and/or output. 

Please test and let me know if you notice any problem.

**Comment by gaow** [comment]
This script works:

```
[step]
param = [1,2,3,4,5]
input:  'a-20.txt', 'b-10.txt'
output: []
run('echo ${input}; echo ${param}')
```
although without `output:[]` it will rerun. Is this the expected behavior?

**Comment by bpeng2000** [comment]
Yes. The problem here is that runtime signature is composed of global and step statement text, and input and output files. We can have runtime signature if users know there is no output or input, but we cannot do that if they are undefined. For example, our tutorial script can be run with different command line arguments but the script is intact so without input/output definition the script will not run correctly.

**Comment by bpeng2000** [comment]
This should have been fixed.
