### ISSUE TITLE
Sorted result for input wildcard

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#81]
Suppose there is this user case:
```
input: 'data/*Input*.bed' , 'data/*Reference*.bed', group_by = 'pairs'
```
One would hope that the input files can match in pairs by common patterns. e.g. `A.Input.1.bed` matches `A.Reference.1.bed`. But currently it is not the case because the ordering is random. I can use `sorted(glob())` for this scenario. I'm just wondering if it can help a little by sort the input from wildcard before continue.

**Comment by bpeng2000** [comment]
This is trivial and is done, but relying on SoS to sort the files is not safe.
