### ISSUE TITLE
Output is no longer aware of 'group_by'

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#82]
For example, if I use `group_by` then `_output` should also be affected by `group_by` to match the input. But it does not seem to be the case now:
```
[step]
input:  'a-20.txt', 'b-10.txt', pattern = '{name}-{par}.txt', group_by = 'single'
output: pattern = '{name}-processed-{par}.txt'
run('echo ${_input}; echo ${_output}; touch ${_output}')
```
Result:

```
INFO: Execute step_0: 
INFO: input:   ['a-20.txt', 'b-10.txt']
a-20.txt
a-processed-20.txt b-processed-10.txt
b-10.txt
a-processed-20.txt b-processed-10.txt
INFO: output:  ['a-processed-20.txt', 'b-processed-10.txt']
```

It seems `${output}` and `${_output}` are the same here now ...

**Comment by bpeng2000** [comment]
Because you used 

```
pattern = '{name}-processed-{par}.txt
```

instead of

```
pattern = '{_name}-processed-{_par}.txt
```

If you use the full version, it generates all output files, which is `_output`. You will have the same `output` but you will lose fine level signature caused by `_output`.

**Comment by gaow** [comment]
Oops I believe it is the 2nd time I've done this ... I actually updated the documentation but I don't understand why I keep forgetting.
