### ISSUE TITLE
Unifying SoS dictionary and list?

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#9]
Snakemake has some magic that allows `input` to be accessed as both list and object with attributes. For example,
it allows

```
input:  reference='seq.fasta'
        bamfiles=['a.bam', 'b.bam']
```

and expressions such as `input.reference`, `input.bamfile`, and `input`. This can be easily achieved with some Python magic
but I am not sure if I should follow it and make SoS more difficult to understand.

Pros:
* It seems nice to name different types of input files.

Cons:
* It does not work well with input options such as `group_by`.
* Unlike snakemake, SoS already allows definition of variables, so users can define

```python
reference='seq.fasta'
bamfiles=['a.bam', 'b.bam']

input: reference, bamfiles
```

and use `input`, `reference`, and `bamfiles` separately. Here `reference` more likely
belongs to `depends`.

For simplicity and mostly the last reason, I incline not to use complicated data structure here.

**Comment by gaow** [comment]
I do not like this with snakemake. Pythonic means that there is only one correct way to do one thing (my understanding, as opposed to Perl), so accessing by index is our only way here -- might look ugly sometimes but always clear.

**Comment by bpeng2000** [comment]
Agreed. I was confused with input and input.subinput. This is not that
useful since SoS can define multiple variables.

Bo
