### ISSUE TITLE
search path or stash directory option for SoS

### ISSUE THREAD

**Issue by bpeng2000** [bpeng2000/SOS#90]
It can be a good or bad feature but we might provide a search path or stash directory option inside `.sos/config.json` to allow SoS to search for specified script and scripts for nested workflows.

**Comment by gaow** [comment]
I do not see why this is bad feature. "stash" by its name implies that there is risk involved and whoever decides to stash stuff should face it :)

**Comment by bpeng2000** [comment]
Option `sos_path` has been implemented. It also works with URL but there is no way to test it yet.
