### ISSUE TITLE
Runtime signature not found when `workdir` is used

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#91]
I cannot trivially reproduce this issue with an example to share. The error message reads: 

```
DEBUG: _output: ['20160408/data_BM.hh', '20160408/PbTree.pdf']
...
TRACE: Deregister 2918
TRACE: Deregister 2895
TRACE: Write signature .sos/.runtime/20160408/data_BM.h53fa5d26136107af53ff45f25d2987d52.exe_info
...
 [Errno 2] No such file or directory: '.sos/.runtime/20160408/data_BM.h53fa5d26136107af53ff45f25d2987d52.exe_info'

```

I do have the expected output file `20160408/data_BM.h5` generated. But the next step cannot be executed due to this message. I cannot find the signature in `./.sos` or `~/.sos`. Let me explore some more. Just in case there is an immediate thought on this.

**Comment by gaow** [comment]
I guess this has something to do with `workdir` now! See this example:

```
[1]
run:
mkdir -p workdir/data

[2]
output: 'data/test.txt'
run: workdir = 'workdir'
touch ${output}

[3]
run: workdir = 'workdir'
echo ${input}
```
Running this I get another error message. 

```
INFO: Execute default_1: 
INFO: input:   []
INFO: output:  unspecified
INFO: Execute default_2: 
INFO: input:   unspecified
INFO: output:  ['data/test.txt']
ERROR: Failed to execute process
"run('touch ${output}\n',workdir = 'workdir')"
[Errno 2] No such file or directory: '.sos/proc_3488'
```

In my original script I did have used `workdir`. Although the errors are different I do think they are related.

**Comment by bpeng2000** [comment]
We need to define the behavior here. The output is clearly `data/test.txt', not `workdir/data/test.txt'. SoS should say 'data/test.txt` not found after step 2, right?

**Comment by gaow** [comment]
Right on my end I should have output be `workdir/data/test.txt`. But I was not properly warned so I did not recognize the problem right away.

**Comment by bpeng2000** [comment]
You should be warned with a patch I just submitted.

**Comment by gaow** [comment]
Great -- thanks a lot!
